# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-08 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Handler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='\u89c6\u56fe\u540d\u79f0')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='\u83dc\u5355\u540d')),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='\u6743\u9650\u540d')),
                ('strcode', models.CharField(max_length=32, verbose_name='\u6743\u9650\u7801')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='\u89d2\u8272\u540d')),
                ('users', models.ManyToManyField(related_name='roles', to='account.User')),
            ],
        ),
        migrations.AddField(
            model_name='permission',
            name='roles',
            field=models.ManyToManyField(related_name='permissions', to='permission.Role'),
        ),
        migrations.AddField(
            model_name='menu',
            name='permissions',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='permission.Permission'),
        ),
        migrations.AddField(
            model_name='handler',
            name='permissions',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='permission.Permission'),
        ),
    ]
